data:
  pointcloud_n: 30000  # 随机采样 3w 个点
  path: /home/neal/projects/SA-ConvONet/data/demo
  pointcloud_file: pointcloud.npz
  padding: 0.1  # 立方体扩展为 +-0.55
  dim: 3  # input dim
model:
  encoder_kwargs:
    hidden_dim: 32
    grid_resolution: 64
    unet3d_kwargs:
      num_levels: 4
      f_maps: 32
      in_channels: 32
      out_channels: 32
  decoder_kwargs:
    hidden_size: 32
  c_dim: 32
training:
  out_dir: out
test:
  model_path: /home/neal/projects/SA-ConvONet/data
  model_file: room_grid64.pt #model.pt #
generation:
  resolution_0: 64  # 地图分辨率
  upsampling_steps: 2
test_optim:
  learning_rate: 0.00003
  decay_rate: 0.3
  n_iter: 720
  n_step: 150  # 150 步后，learning rate*0.3；经验上来说，loss = 1150 就有不错的效果
  batch_size: 6         
  npoints_surf: 1536    # surface 点个数
  npoints_nonsurf: 512  # noise 点个数
  sigma: 0.1            # 噪声的尺度
  threshold: [0.65, 0.7, 0.75]  # 判断是否为 surface 的阈值